Flake8 breaks backward compatibility
ValueError: Error code '#' supplied to 'ignore'
option does not match '^[A-Z]{1,3}[0-9]{0,3}$'
https://github.com/PyCQA/flake8/issues/1795